<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOkIQS9a\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOkIQS9a/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerOkIQS9a.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerOkIQS9a\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerOkIQS9a\App_KernelProdContainer([
    'container.build_hash' => 'OkIQS9a',
    'container.build_id' => 'ea19067d',
    'container.build_time' => 1677094156,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOkIQS9a');
